### PR TITLE
Configure JAVA_HOME for Windows startup script

### PR DESCRIPTION
**Pull request by jcvitanovic**
Add an option to configure java jre path for Windows startup script

Adresses #235 

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/sls-packaging/236)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/sls-packaging](https://github.com/palantir/sls-packaging), @jcvitanovic! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by uschi2000** [comment]
I think we want the java path to be a relative path (relative to where the command is run from): this is only to support bundled JREs. does that constraint work with your use case?

**Comment by jcvitanovic** [comment]
This is exactly the use case I need this for. It is already relative to where the command is run from, I tested this branch  and I got my service to start up with java home set to service/lib/jre path, am I missing something?

**Comment by uschi2000** [comment]
OK. If it's relative, then we should be able to use just one javaPath of the form `foo/bar/baz` and then translate it to something windows-looking behind the scenes?

**Comment by iamdanfox** [comment]
@jcvitanovic looks like there's just a couple more commits to get this merged - would you be able to re-use the existing `javaHome` parameter (as it seems unlikely to need one dist with a pre-specified unix `javaHome` to also work on windows)?

**Comment by jcvitanovic** [comment]
@iamdanfox  -> yea agreed.
sorry, this fell of my radar, I'll push the changes as soon as I get a chance

**Comment by iamdanfox** [comment]
Closing out stale PR

**Pull request closed without merging**
