### PR TITLE
Append to startup log rather than overwrite

### PR DESCRIPTION
**Pull request by ellisjoe**

### CODE REVIEW

**Comment by iamdanfox** [comment]
@ellisjoe for long-lived installations, won't this lead to the startup log growing infinitely?  Nothing is set up to compress/truncate the startup log...

**Comment by ellisjoe** [comment]
yeah I don't actually know if this is the right solution. the issue was that jvms were OOMing which dumps some diagnostic logs to stdout, then our deployment infra was restarting the service automatically and overwriting the startup log. open to other ideas here

**Comment by markelliot** [comment]
we'd need to pipe to a real log rotator -- the startup stuff here could use another pass

**Comment by dansanduleac** [comment]
gone stale

**Comment by fryz** [comment]
Filed https://github.com/palantir/sls-packaging/issues/286 to keep track of this.

**Pull request closed without merging**
