### PR TITLE
Change artifact extension to sls.tgz

### LINKED ISSUE #105: File names must end in sls.tgz instead of tgz

### PR DESCRIPTION
**Pull request by bmoylan**
Fixes #105

---

This change is [Reviewable](https://reviewable.io/reviews/palantir/gradle-java-distribution/108)

### CODE REVIEW

**Comment by bmoylan** [comment]
need to update README and maybe add a test for this getting into the `pom.xml` created by `maven-publish`

**Comment by markelliot** [comment]
@bmoylan could you update the readme as part of this PR, please?

**Comment by bmoylan** [comment]
Yes, will do it right now. When are we planning on open-sourcing (making public) the spec repo so that we can link to it from the readme here? The `sls` seems kind of randomly thrown in without the context.

**Comment by markelliot** [comment]
I'm not sure what we're waiting on w/r/t flipping the switch on the other repo, but this repo does describe its own intent " In particular, this plugin packages a project into a common deployment structure with a simple start script", so not too random.

**Comment by bmoylan** [comment]
Updated filename in readme

**Pull request merged**
