### PR TITLE
Demonstrate main class inference failure

### PR DESCRIPTION
**Pull request by ferozco**
## Before this PR
We did not demonstrate what would happen if multiple main classes were discovered

## After this PR
Added a test showing that we fail we a precise error message when multiple main classes are discovered

## Possible downsides?
N/A

### CODE REVIEW

**Comment by markelliot** [comment]
Thanks! Should we allow for specifying which main class when there’s more than one present? I imagine some servers may still provide CLI main classes, and we probably shouldn’t outright prevent those from building.

**Comment by ferozco** [comment]
Users can actually still specify the main class like used to. The main class inference just attempts to provide a default if non is specified. I've also updated the README to make that more clear

**Comment by markelliot** [comment]
Makes sense. Could we include test coverage for the multiple-classes but user specifies which one case, too, please?

**Comment by ferozco** [comment]
@markelliot I've added another test. Is there anything else you'd like?

**Review by markelliot — APPROVED** [review]

**Pull request merged**
