### PR TITLE
Accept orderable rc-snapshots

### PR DESCRIPTION
**Pull request by emalaj**
and remove beta versions.

order should be: `release snapshot > normal release > release candidate (rc) snapshot > rc`

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/sls-packaging/206)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/sls-packaging](https://github.com/palantir/sls-packaging), @emalaj! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Review by darora — APPROVED** [review]

**Review by uschi2000 — APPROVED** [review]

**Comment by uschi2000** [comment]
Cheers!

**Comment by emalaj** [comment]
@uschi2000 do you mind cutting another release so we can start picking this up?

**Comment by uschi2000** [comment]
done

**Pull request merged**
