### PR TITLE
Configure tasks synchronously

### PR DESCRIPTION
**Pull request by henryptung**
Targets #52.

Test `build.gradle`:

``` groovy
distribution {
    serviceName "my-service"
    mainClass "dummy.service.MainClass"
    args "hello"
}

dependencies {
    compile "com.palantir.gradle.javadist:gradle-java-distribution:$javaDistributionVersion"
}

println "Class-Path: ${manifestClasspathJar.manifest.attributes["Class-Path"]}"
println "distTar output: ${distTar.outputs.files.singleFile}"

afterEvaluate {
    println "Class-Path (afterEvaluate): ${manifestClasspathJar.manifest.attributes["Class-Path"]}"
    println "distTar output (afterEvaluate): ${distTar.outputs.files.singleFile}"
}
```

With 0.5.0:

```
Class-Path: null
distTar output: /home/htung/dev/sandbox/build/distributions/sandbox.tgz
Class-Path (afterEvaluate): gradle-java-distribution-0.5.0.jar sandbox.jar
distTar output (afterEvaluate): /home/htung/dev/sandbox/build/distributions/my-service.tgz
```

After patch:

```
Class-Path: gradle-java-distribution-0.5.0-4-gd49c1de.dirty-sources.jar gradle-java-distribution-0.5.0-4-gd49c1de.dirty.jar sandbox.jar
distTar output: /home/htung/dev/sandbox/build/distributions/my-service.tgz
Class-Path (afterEvaluate): gradle-java-distribution-0.5.0-4-gd49c1de.dirty-sources.jar gradle-java-distribution-0.5.0-4-gd49c1de.dirty.jar sandbox.jar
distTar output (afterEvaluate): /home/htung/dev/sandbox/build/distributions/my-service.tgz
```

### CODE REVIEW

**Comment by markelliot** [comment]
According to https://discuss.gradle.org/t/whats-the-difference-between-plugin-conventions-vs-plugin-extensions/5523 conventions are no longer recommended. Perhaps there's a fix here which doesn't involve such a large change.

**Comment by markelliot** [comment]
e.g. I suspect this whole thing is fixable by making the classpath computation lazy (by deferring it as a lambda)

**Comment by henryptung** [comment]
Er, the classpath computation is lazy in the new impl, but that's not the primary problem here; the configuration of the distTar name is.

The reason conventions were deprecated is namespacing concerns, where method names could collide between plugins. In this case, the distribution extension already made `distribution` a closure-taking method, which could collide with other plugins; this implementation should have no more API collision surface area than the original.

**Comment by markelliot** [comment]
why isn't this solved by just moving `distTar.configure(ext)` then?

**Comment by henryptung** [comment]
Where would you suggest moving it in this case? I tried looking for a reasonable place to put it, but plugin application is too early (the `DistributionExtension` is not configured yet), and given the current API, I'm not sure you can schedule anything to run after the `distribution { }` closure automatically.

I chose instead to move code in bulk; there's very little actual change to the code; it just moves task creation somewhat later (plugin application time -> post-`distribution { }` time) and moves task configuration earlier (`afterEvaluate` -> post-`distribution { }` time), to minimize behavior change.

**Comment by henryptung** [comment]
From a more abstract POV, Gradle configuration is moving towards [rule-based model configuration](https://docs.gradle.org/current/userguide/software_model.html). That model seems to be based around immutable state, with a dependency resolver that schedules execution of configuration blocks based on their state dependencies.

But without that resolver/scheduler (which doesn't seem to exist yet), there's not a way to automagically schedule my `almanacPublish` task configuration after `distTar` task configuration; at least, if `distTar` task configuration is done as early as possible (during project evaluation), I can just move my task declaration below that point, instead of moving it into `afterEvaluate` (which in turn would force anything depending on that task into `afterEvaluate`, etc.).

**Comment by markelliot** [comment]
I'm still a bit puzzled why this shows up for you, in my almanacPublish blocks I'm just referencing `artifact distTar`, and I get the right names.

**Comment by markelliot** [comment]
I'm going to close this in favor of #56

**Comment by markelliot** [comment]
...if you want to contribute the configurable classpath thing you're welcome to do so, but obv. doesn't need the rest of the change on this PR.

**Pull request closed without merging**
