### PR TITLE
Support specifying serviceDependency for service distributions

### PR DESCRIPTION
**Pull request by uschi2000**
This change is [Reviewable](https://reviewable.io/reviews/palantir/gradle-java-distribution/166)

### CODE REVIEW

**Review by markelliot — APPROVED** [review]

**Comment by bmoylan** [comment]
Assets can also have service dependencies (e.g. contour-app asset depends on contour-dispatch service), so we should add it to the asset plugin as well.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/groovy/com/palantir/gradle/dist/service/JavaDistributionPlugin.groovy, line 92 at r1](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/166#-KbJGji4EKBKhwQzYiFr:-KbJGji4EKBKhwQzYiFs:b-fdb4pg) ([raw file](https://github.com/palantir/gradle-java-distribution/blob/40271a3af6c72be4dd3c1a9bb7c7aec4239f58c9/src/main/groovy/com/palantir/gradle/dist/service/JavaDistributionPlugin.groovy#L92)):*
> ```Groovy
>             if (distributionExtension.manifestExtensions.containsKey("service-dependencies")) {
>                 throw new IllegalArgumentException("Use serviceDependencies configuration option instead of setting " +
>                         "'service-dependency' key in manifestExtensions")
> ```

s/dependency/dependencies

---

*[src/main/groovy/com/palantir/gradle/dist/service/ServiceDistributionExtension.groovy, line 94 at r1](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/166#-KbJIPKE0L8xT51K2nhB:-KbJIPKE0L8xT51K2nhC:bcpod6g) ([raw file](https://github.com/palantir/gradle-java-distribution/blob/40271a3af6c72be4dd3c1a9bb7c7aec4239f58c9/src/main/groovy/com/palantir/gradle/dist/service/ServiceDistributionExtension.groovy#L94)):*
> ```Groovy
>     }
> 
>     public void serviceDependency(String serviceGroup, String serviceName, String minVersion, String maxVersion, String recommendedVersion) {
> ```

Writing out 5 string arguments in a Gradle file feels a bit unwieldy. Can the argument be something key:value? Not sure whether a map, a new ServiceDependencyExtension type, or the ServiceDependency type itself. This also gives you more flexibility if you want to add fields in the future.

Another option would be to let the user construct their `manifestExtensions` with nested maps and then validate keys we recognize after the fact.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/166#-:-KbJKJfZ4P9j-um2Xmch:bovsufo)*

**Comment by uschi2000** [comment]
will do in next commit

---

Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/groovy/com/palantir/gradle/dist/service/JavaDistributionPlugin.groovy, line 92 at r1](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/166#-KbJGji4EKBKhwQzYiFr:-KbKjRcwHRFW12u8ORt1:bb6un1j) ([raw file](https://github.com/palantir/gradle-java-distribution/blob/40271a3af6c72be4dd3c1a9bb7c7aec4239f58c9/src/main/groovy/com/palantir/gradle/dist/service/JavaDistributionPlugin.groovy#L92)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

s/dependency/dependencies
</blockquote></details>

Done

---

*[src/main/groovy/com/palantir/gradle/dist/service/ServiceDistributionExtension.groovy, line 94 at r1](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/166#-KbJIPKE0L8xT51K2nhB:-KbKp7l4kuAT_sHZzFbO:bb7f2mf) ([raw file](https://github.com/palantir/gradle-java-distribution/blob/40271a3af6c72be4dd3c1a9bb7c7aec4239f58c9/src/main/groovy/com/palantir/gradle/dist/service/ServiceDistributionExtension.groovy#L94)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

Writing out 5 string arguments in a Gradle file feels a bit unwieldy. Can the argument be something key:value? Not sure whether a map, a new ServiceDependencyExtension type, or the ServiceDependency type itself. This also gives you more flexibility if you want to add fields in the future.

Another option would be to let the user construct their `manifestExtensions` with nested maps and then validate keys we recognize after the fact.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/166#-:-KbKp9sNFyF58pasWQ1N:b9cqvqt)*

**Comment by uschi2000** [comment]
done

---

Review status: 1 of 7 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/166#-:-KbKtExychRVoZZBtUmQ:bb7f2mf)*

**Comment by uschi2000** [comment]
readme for review

---

Review status: 1 of 10 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/166#-:-KbKug6zC7F1USta1Sti:bxluti4)*

**Comment by uschi2000** [comment]
Moving on. Let me know if there's anything else, @bmoylan

**Comment by bmoylan** [comment]
LGTM thanks rob!

**Pull request merged**
