### PR TITLE
Add a refresh command

### PR DESCRIPTION
**Pull request by sfackler**
Intended to support managed live reload

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/gradle-java-distribution/153)

### CODE REVIEW

**Comment by markelliot** [comment]
I think we're trying to move away from a world where we add more options to `init.sh`. I assume you want the deployability software we run to have a configurable location to invoke, that could happen with another shell script calling go-java-launcher with launcher-refresh.yml, rather than invoking the init script.

**Comment by markelliot** [comment]
For reference, we're currently talking about ways to remove the `check` option.

**Comment by sfackler** [comment]
Yep, if the deployability software allowed the refresh command to be configured then this would be unnecessary.

**Comment by markelliot** [comment]
Interesting, thought it was configurable. Worth filing a ticket with those folks, would prefer to hold on this until we get that feedback.

**Comment by sfackler** [comment]
Filed an issue on that tracker and cc'd you on it.

**Comment by uschi2000** [comment]
Can this be closed?

**Comment by sfackler** [comment]
Has the upstream issue been resolved?

**Comment by uschi2000** [comment]
I haven't done any investigation

**Comment by sfackler** [comment]
Handled by #195

**Pull request closed without merging**
