### PR TITLE
Write service-dependencies block with kebab-case instead of camelCase

### PR DESCRIPTION
**Pull request by uschi2000**
This change is [Reviewable](https://reviewable.io/reviews/palantir/sls-packaging/182)

### CODE REVIEW

**Comment by bmoylan** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/ServiceDependency.groovy, line 10 at r1](https://reviewable.io:443/reviews/palantir/sls-packaging/182#-Kc45O8lKOxe68PPpFw8:-Kc45O8lKOxe68PPpFw9:bozmgch) ([raw file](https://github.com/palantir/sls-packaging/blob/6b02f23e182cab27c875972ad52714692816b35d/gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/ServiceDependency.groovy#L10)):*
> ```Groovy
>     String productName
>     String minVersion
>     String maxVersion
> ```

`minVersion` and `maxVersion` are optional as well, so I think that means they should be @Nullable

---

*[gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/tasks/CreateManifestTask.groovy, line 83 at r1](https://reviewable.io:443/reviews/palantir/sls-packaging/182#-Kc45EDc4bYnhgwWL_Ya:-Kc45EDc4bYnhgwWL_Yb:bb8o3gr) ([raw file](https://github.com/palantir/sls-packaging/blob/6b02f23e182cab27c875972ad52714692816b35d/gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/tasks/CreateManifestTask.groovy#L83)):*
> ```Groovy
>                    List<ServiceDependency> serviceDependencies) {
>         // Serialize service-dependencies, add them to manifestExtensions
>         def mapper = new ObjectMapper().setSerializationInclusion(JsonInclude.Include.NON_NULL).setPropertyNamingStrategy(new KebabCaseStrategy())
> ```

Apologies for being a Jackson noob, this means that keys with `null` values are omitted right? (that's what we want)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/sls-packaging/182)*

**Comment by uschi2000** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/ServiceDependency.groovy, line 10 at r1](https://reviewable.io:443/reviews/palantir/sls-packaging/182#-Kc45O8lKOxe68PPpFw8:-Kc49MNxmr1vUT57eFoB:b-896fix) ([raw file](https://github.com/palantir/sls-packaging/blob/6b02f23e182cab27c875972ad52714692816b35d/gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/ServiceDependency.groovy#L10)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

`minVersion` and `maxVersion` are optional as well, so I think that means they should be @Nullable
</blockquote></details>

Done.

---

*[gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/tasks/CreateManifestTask.groovy, line 83 at r1](https://reviewable.io:443/reviews/palantir/sls-packaging/182#-Kc45EDc4bYnhgwWL_Ya:-Kc49KQU1G3Qad-QqGkV:b-jp377f) ([raw file](https://github.com/palantir/sls-packaging/blob/6b02f23e182cab27c875972ad52714692816b35d/gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/tasks/CreateManifestTask.groovy#L83)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

Apologies for being a Jackson noob, this means that keys with `null` values are omitted right? (that's what we want)
</blockquote></details>

correct

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/sls-packaging/182)*

**Comment by bmoylan** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/sls-packaging/182#-:-Kc4AvzRUVuxUwO3R67G:bnfp4nl)*

**Comment by bmoylan** [comment]
I don't have write access on this to give a github approval

**Pull request merged**
