### PR TITLE
Add startDelay property to DistributionExtension

### PR DESCRIPTION
**Pull request by henryptung**
Configures wait delay before checking liveness of the application
process.

### CODE REVIEW

**Comment by markelliot** [comment]
I think it'd be better to do this with a fixed maximum wait for start time, similar to the way Dan modified the fixed maximum wait for stop time. See #59.

**Comment by henryptung** [comment]
Agreed, there's an easy gate for figuring out whether a process is stopped via PID existence. Do you have a similar analogue for startup in mind?

**Comment by markelliot** [comment]
The is_process_active function used in the stop loop can also be used in the start loop, it checks the process table using the PID file, which is created before the current sleep call.

**Comment by henryptung** [comment]
Ah, sorry, I should have explained the use case first, my bad.

This PR targets the case where service startup requires initializing or checking some backend, and may fail N seconds after the Java process is created.

If I understand correctly, `is_process_active` checks if the process exists, but I'm trying to check beyond "Java PID exists", to "was configuration parsed correctly" and "are backends alive + properly initialized".

Not sure if that's within scope of this script, but "process starts but exits very soon after" is probably fairly common (malformed configuration).

**Comment by markelliot** [comment]
Ah, makes sense. Could we just add an optional 2nd check which checks the process lives for at least N seconds after it starts, then?

**Comment by uschi2000** [comment]
Closing due to inactivity. Feel free to reopen.

**Pull request closed without merging**
