### PR TITLE
Support for setting the productType to daemon.v1

### PR DESCRIPTION
**Pull request by SerialVelocity**
This change is [Reviewable](https://reviewable.io/reviews/palantir/sls-packaging/183)

### CODE REVIEW

**Comment by SerialVelocity** [comment]
I don't think any other changes are required for this to work, right? @uschi2000

**Comment by uschi2000** [comment]
I missed this in the previous PR, unfortunately: How hard would it be to assert that the asset plugin produces asset.v1 only and the service plugin produces service&daemon only?

**Comment by SerialVelocity** [comment]
I can look into that but the tests don't pass locally for me so it's hard to see if it is working properly.

**Comment by uschi2000** [comment]
Are you building in Macos?

**Comment by SerialVelocity** [comment]
Yes. Thinking about it more, it might be to do with me having my gradle set to be parallel by default in my `~/.gradle/gradle.properties`

I'm also using a hack to work around this for now:
```
distribution.class.superclass.superclass.metaClass.setAttribute(distribution, 'productType', 'daemon.v1')
```

**Comment by uschi2000** [comment]
is this still needed? if so, please rebase onto develop.

**Comment by SerialVelocity** [comment]
We're removing our daemon soon so no.

**Pull request closed without merging**
