### PR TITLE
use gradle project name by default

### PR DESCRIPTION
**Pull request by ellisjoe**
This change is [Reviewable](https://reviewable.io/reviews/palantir/sls-packaging/227)

### CODE REVIEW

**Comment by iamdanfox** [comment]
probably worth a cheeky little unit test here - e.g. how would this behave with nested projects?

**Review by uschi2000 — APPROVED** [review]

**Comment by ellisjoe** [comment]
@iamdanfox added a test for nested projects

**Comment by iamdanfox** [comment]
🚢 it

**Comment by ellisjoe** [comment]
think I need to get added to the repo for the tests to run (they don't like my fork)

**Comment by ellisjoe** [comment]
closing in favor of non forked PR https://github.com/palantir/sls-packaging/pull/228

**Pull request closed without merging**
