### PR TITLE
Change VersionMatcher format

### PR DESCRIPTION
**Pull request by mnazbro**
Version matcher must:
 1. Contain at least one wildcard (x).
 2. Must not contain a wildcard in a larger position than a
    a non-wildcard version (e.g. x.1.2 is not valid)

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/sls-packaging/191)

### CODE REVIEW

**Comment by mnazbro** [comment]
@gdearment @uschi2000 @bmoylan

**Comment by uschi2000** [comment]
Looks good. Need to make corresponding change to sls-spec too.

**Comment by uschi2000** [comment]
is this still relevant, @mnazbro ?

**Comment by mnazbro** [comment]
This change is still relevant. The sls-spec has already been changed accordingly. A single regex was used instead in the spec.

**Review by uschi2000 — APPROVED** [review]

**Comment by uschi2000** [comment]
Looks good, but doesn't compile.

**Comment by mnazbro** [comment]
Updated with fixed code. I tried modifying it in the GitHub UI and that caused the compilation error.

**Pull request merged**
