### PR TITLE
Fix: Downgrade jackson to 2.11.1

### PR DESCRIPTION
**Pull request by robert3005**
## After this PR
==COMMIT_MSG==
Downgrade jackson to 2.11.1 to avoid jackson bugs
==COMMIT_MSG==

### CODE REVIEW

**Comment by iamdanfox** [comment]
Why make this change to gradle plugins?

**Comment by robert3005** [comment]
I have a repo that has a service and a gradle plugin and it gets higher version from this plugin. I am happy to force downgrade in repo but I thought more people are going to have the same problem

**Comment by carterkozak** [comment]
+1 for uniformity.

**Comment by ferozco** [comment]
👍

**Comment by iamdanfox** [comment]
🦜

**Pull request merged**
