### PR TITLE
Use go-init 1.5.0

### PR DESCRIPTION
**Pull request by cbrockington**

### CODE REVIEW

**Comment by cbrockington** [comment]
@iamdanfox is the new requirement on palantir.bintray.com both expected and acceptable?

**Comment by cbrockington** [comment]
in fact also @dansanduleac since I feel I remember you previously talking to @gregakinman about this

**Comment by ferozco** [comment]
@cbrockington I believe that the bintray requirement is only for external consumption

**Comment by cbrockington** [comment]
Ah ok, since the tests run externally that makes sense.  Is this good to merge and rc?

**Review by ferozco — APPROVED** [review]
can you follow up by updating a few services and ensuring everything is in working order

**Comment by gregakinman** [comment]
sweet, thanks @cbrockington!

**Pull request merged**
