### PR TITLE
Add 'product-type: service.v1' field to manifest.yml, fixes #107

### LINKED ISSUE #107: manifest.yml needs to include "layoutVersion" field
layoutVersion indicates the version of the directory&file layout

### PR DESCRIPTION
**Pull request by uschi2000**
This change is [Reviewable](https://reviewable.io/reviews/palantir/gradle-java-distribution/135)

### CODE REVIEW

**Comment by bmoylan** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/main/resources/manifest.yml, line 5 at r1](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/135#-KUt7uBDjV6jJGh7iZgu:-KUt7uBDjV6jJGh7iZgv:buhjkus) ([raw file](https://github.com/palantir/gradle-java-distribution/blob/1b527d7bb3c1ca6f8032f92034360509741e19e9/src/main/resources/manifest.yml#L5)):_

> ``` YAML
> product-name: @serviceName@
> product-version: @serviceVersion@
> layout-type: service.v1
> ```

Are we going to make this configurable/overridable?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/135)_

**Comment by uschi2000** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/main/resources/manifest.yml, line 5 at r1](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/135#-KUt7uBDjV6jJGh7iZgu:-KUtAu1NZI76poEzwcMn:b-rgal2k) ([raw file](https://github.com/palantir/gradle-java-distribution/blob/1b527d7bb3c1ca6f8032f92034360509741e19e9/src/main/resources/manifest.yml#L5)):_
<details><summary>

<i>Previously, bmoylan (Brad Moylan) wrote…</i></summary>



> Are we going to make this configurable/overridable?
> </details>
> not yet (because there is no other option). happy to make this this configurable once we have alternatives. or maybe we'll just upgrade the version at some point and only support v2.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/135)_

**Comment by uschi2000** [comment]
Anything left here, @markelliot @bmoylan ?

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/135#-:-KUwqd_YnQ94wGylRwm3:b-tu4dr)_

**Comment by bmoylan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/135#-:-KUwr_ov_oxNlAjaow1b:bnfp4nl)_

**Pull request merged**
