### PR TITLE
[improvement] When enabled, hprof heap dumps are written to var/log

### LINKED ISSUE #423: Specify hprof directory
## What happened?

The current setting for `HeapDumpPath` is currently implicitly `-XX:HeapDumpPath=./java_pid<pid>.hprof`.

## What did you want to happen?

In the same spirit as https://github.com/palantir/sls-packaging/pull/314, specify `-XX:HeapDumpPath=var/log`

### PR DESCRIPTION
**Pull request by raiju**
Fixes #423

### CODE REVIEW

**Comment by ferozco** [comment]
@raiju We set `CrashOnOutOfMemoryError` so no heap dump should be produced

**Comment by carterkozak** [comment]
@ferozco The two parameters are not mutually exclusive, the crash occurs after a heap dump is written to disk. While we do not enable `-XX:+HeapDumpOnOutOfMemoryError` by default, it is reasonable to enable while monitoring/debugging a failing service.

**Comment by ferozco** [comment]
Ok, I thought that they were. I'm hesitant to encourage enabling heap dumps though.  Enabling heap dumps can be a foot gun since a bad release of a single service could crash multiple times taking down the box with it because the disk fills up.

**Comment by raiju** [comment]
@ferozco This isn't enabling heap dumps. It's only specifying where heap dumps are written if enabled so we can hook it into our metrics (alert on heap dump creation), and is in a place where there is some file rotation policy in place.

**Comment by ferozco** [comment]
👍

**Comment by robert3005** [comment]
@raiju can you point me to the services which are producing heap dumps that you care about?

**Pull request merged**
