### PR TITLE
Generate '.yml' instead of '.yaml' for manifest and configuration

### PR DESCRIPTION
**Pull request by nmiyake**
@markelliot , @dtolnay , @bmoylan 

If this checks out, we'll want to merge this once https://github.com/palantir/deployd/pull/1124 is merged (and released?)

### CODE REVIEW

**Comment by markelliot** [comment]
lgtm

**Comment by nmiyake** [comment]
Great! All of the Skylab changes have merged, so the next release should be able to support this. Will merge this once we have the next Skylab release ( @bmoylan , should be this week, right?) to ensure that there's a release of Skylab that can actually deal with the generated artifacts.

**Comment by nmiyake** [comment]
@markelliot , when this merges, should this bump to 0.4.2, 0.5.0, or no bump and stay at 0.4.1? I think 0.4.2 makes the most sense, but wanted to check in case you have a specific system.

**Comment by markelliot** [comment]
0.5.0, it's technically a break.

Prefer that I merge/release here, just let me know when you're g2g on your side?

**Comment by nmiyake** [comment]
Yup, all of that sounds good. Will let you know when we’re for you to merge
and release — should be in the next few days (we just want to make sure that
we have shipped a Skylab release that will handle the newly generated things
before you merge into gradle-java-dist)

From:  Mark Elliot notifications@github.com
Reply-To:  palantir/gradle-java-distribution
<reply+00411da1da63701107c45bfa9079932345f5deaedca4c6b492cf0000000112c00b5e9
2a169ce07ac7212@reply.github.com>
Date:  Tuesday, January 26, 2016 at 8:36 PM
To:  palantir/gradle-java-distribution
gradle-java-distribution@noreply.github.com
Cc:  Nick Miyake nmiyake@palantir.com
Subject:  Re: [gradle-java-distribution] Generate '.yml' instead of '.yaml'
for manifest and configuration (#44)

0.5.0, it's technically a break.

Prefer that I merge/release here, just let me know when you're g2g on your
side? 

—
Reply to this email directly or view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_palantir_gr
adle-2Djava-2Ddistribution_pull_44-23issuecomment-2D175388946&d=CwMCaQ&c=izl
c9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=EiIqkm9OeP9DZ0tLChS3gQWPsy5yzGdFB
hxx6fuNVx0&m=mbl8kZ3YoJZ_kVc5Z-4nEt-bQiLppSOVwXONpbJC9FE&s=buqXm_NYnbQxPsV46
HTtioxAJq_GfphKzc73izE3I8M&e=> .

**Comment by nmiyake** [comment]
@markelliot , Skylab that supports this has now been released, so please merge and bump version at your convenience.

**Comment by markelliot** [comment]
agh, can you rebase instead of merging the upstream branch?

**Comment by nmiyake** [comment]
OK will do

**Pull request merged**
